scan_filter_chain:
#- name: shadows
#  type: ScanShadowsFilter
#  params:
#    min_angle: 5
#    max_angle: 250
#    neighbors: 3
#    window: 1
- type: LaserArrayFilter
  name: laser_median_filter
  params: 
    range_filter_chain:
      - name: median_5
        type: MultiChannelMedianFilterFloat 
        params:
          number_of_observations: 7
          unused: 0
    intensity_filter_chain:
      - name: median_5
        type: MultiChannelMedianFilterFloat 
        params:
          number_of_observations: 5
          unused: 10