//#line 2 "/home/sblume/ros/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"
// *********************************************************
// 
// File autogenerated for the iav_legtrack package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

/***********************************************************
 * Software License Agreement (BSD License)
 *
 *  Copyright (c) 2008, Willow Garage, Inc.
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   * Neither the name of the Willow Garage nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 ***********************************************************/

// Author: Blaise Gassend


#ifndef __iav_legtrack__IAVLEGTRACKCONFIG_H__
#define __iav_legtrack__IAVLEGTRACKCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/config_init_mutex.h>

namespace iav_legtrack
{
  class IAVLegTrackConfigStatics;
  
  class IAVLegTrackConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(IAVLegTrackConfig &config, const IAVLegTrackConfig &max, const IAVLegTrackConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const IAVLegTrackConfig &config1, const IAVLegTrackConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, IAVLegTrackConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const IAVLegTrackConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, IAVLegTrackConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const IAVLegTrackConfig &config) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T IAVLegTrackConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (IAVLegTrackConfig::* field);

      virtual void clamp(IAVLegTrackConfig &config, const IAVLegTrackConfig &max, const IAVLegTrackConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const IAVLegTrackConfig &config1, const IAVLegTrackConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, IAVLegTrackConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const IAVLegTrackConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, IAVLegTrackConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const IAVLegTrackConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }
    };

//#line 51 "./IAVLegTrack.cfg"
      double max_laser_range;
//#line 53 "./IAVLegTrack.cfg"
      double arc_min_aperture;
//#line 54 "./IAVLegTrack.cfg"
      double arc_max_aperture;
//#line 55 "./IAVLegTrack.cfg"
      double arc_std_max;
//#line 57 "./IAVLegTrack.cfg"
      double segmentation_threshold;
//#line 59 "./IAVLegTrack.cfg"
      double line_min_distance;
//#line 60 "./IAVLegTrack.cfg"
      double line_error_threshold;
//#line 62 "./IAVLegTrack.cfg"
      double max_leg_diameter;
//#line 63 "./IAVLegTrack.cfg"
      double min_leg_diameter;
//#line 65 "./IAVLegTrack.cfg"
      bool do_circles;
//#line 66 "./IAVLegTrack.cfg"
      bool do_lines;
//#line 67 "./IAVLegTrack.cfg"
      bool do_legs;
//#line 68 "./IAVLegTrack.cfg"
      bool iav_do_lines;
//#line 69 "./IAVLegTrack.cfg"
      bool safe_circle_corners;
//#line 138 "/home/sblume/ros/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        if ((*i)->fromMessage(msg, *this))
          count++;
      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("IAVLegTrackConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toMessage(msg, *this);
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      __toMessage__(msg, __param_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->fromServer(nh, *this);
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const IAVLegTrackConfig &__max__ = __getMax__();
      const IAVLegTrackConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const IAVLegTrackConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const IAVLegTrackConfig &__getDefault__();
    static const IAVLegTrackConfig &__getMax__();
    static const IAVLegTrackConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    
  private:
    static const IAVLegTrackConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void IAVLegTrackConfig::ParamDescription<std::string>::clamp(IAVLegTrackConfig &config, const IAVLegTrackConfig &max, const IAVLegTrackConfig &min) const
  {
    return;
  }

  class IAVLegTrackConfigStatics
  {
    friend class IAVLegTrackConfig;
    
    IAVLegTrackConfigStatics()
    {
//#line 51 "./IAVLegTrack.cfg"
      __min__.max_laser_range = 0.0;
//#line 51 "./IAVLegTrack.cfg"
      __max__.max_laser_range = 30.0;
//#line 51 "./IAVLegTrack.cfg"
      __default__.max_laser_range = 8.0;
//#line 51 "./IAVLegTrack.cfg"
      __param_descriptions__.push_back(IAVLegTrackConfig::AbstractParamDescriptionConstPtr(new IAVLegTrackConfig::ParamDescription<double>("max_laser_range", "double", 0, "Maximum laser range", "", &IAVLegTrackConfig::max_laser_range)));
//#line 53 "./IAVLegTrack.cfg"
      __min__.arc_min_aperture = 0.0;
//#line 53 "./IAVLegTrack.cfg"
      __max__.arc_min_aperture = 10.0;
//#line 53 "./IAVLegTrack.cfg"
      __default__.arc_min_aperture = 2.0;
//#line 53 "./IAVLegTrack.cfg"
      __param_descriptions__.push_back(IAVLegTrackConfig::AbstractParamDescriptionConstPtr(new IAVLegTrackConfig::ParamDescription<double>("arc_min_aperture", "double", 0, "Minimum angle of inscribed angles of a potential arc in RAD", "", &IAVLegTrackConfig::arc_min_aperture)));
//#line 54 "./IAVLegTrack.cfg"
      __min__.arc_max_aperture = 0.0;
//#line 54 "./IAVLegTrack.cfg"
      __max__.arc_max_aperture = 10.0;
//#line 54 "./IAVLegTrack.cfg"
      __default__.arc_max_aperture = 3.0;
//#line 54 "./IAVLegTrack.cfg"
      __param_descriptions__.push_back(IAVLegTrackConfig::AbstractParamDescriptionConstPtr(new IAVLegTrackConfig::ParamDescription<double>("arc_max_aperture", "double", 0, "Maximum angle of inscribed angles of a potential arc in RADin RAD", "", &IAVLegTrackConfig::arc_max_aperture)));
//#line 55 "./IAVLegTrack.cfg"
      __min__.arc_std_max = 0.0;
//#line 55 "./IAVLegTrack.cfg"
      __max__.arc_std_max = 1.0;
//#line 55 "./IAVLegTrack.cfg"
      __default__.arc_std_max = 0.25;
//#line 55 "./IAVLegTrack.cfg"
      __param_descriptions__.push_back(IAVLegTrackConfig::AbstractParamDescriptionConstPtr(new IAVLegTrackConfig::ParamDescription<double>("arc_std_max", "double", 0, "Maximum allowed standard deviation od inscribed angles", "", &IAVLegTrackConfig::arc_std_max)));
//#line 57 "./IAVLegTrack.cfg"
      __min__.segmentation_threshold = 0.0;
//#line 57 "./IAVLegTrack.cfg"
      __max__.segmentation_threshold = 10.0;
//#line 57 "./IAVLegTrack.cfg"
      __default__.segmentation_threshold = 0.2;
//#line 57 "./IAVLegTrack.cfg"
      __param_descriptions__.push_back(IAVLegTrackConfig::AbstractParamDescriptionConstPtr(new IAVLegTrackConfig::ParamDescription<double>("segmentation_threshold", "double", 0, "Distance threshold for (jump edge) detection for segments.", "", &IAVLegTrackConfig::segmentation_threshold)));
//#line 59 "./IAVLegTrack.cfg"
      __min__.line_min_distance = 0.0;
//#line 59 "./IAVLegTrack.cfg"
      __max__.line_min_distance = 10.0;
//#line 59 "./IAVLegTrack.cfg"
      __default__.line_min_distance = 0.12;
//#line 59 "./IAVLegTrack.cfg"
      __param_descriptions__.push_back(IAVLegTrackConfig::AbstractParamDescriptionConstPtr(new IAVLegTrackConfig::ParamDescription<double>("line_min_distance", "double", 0, "Minimum length of a line", "", &IAVLegTrackConfig::line_min_distance)));
//#line 60 "./IAVLegTrack.cfg"
      __min__.line_error_threshold = 0.0;
//#line 60 "./IAVLegTrack.cfg"
      __max__.line_error_threshold = 10.0;
//#line 60 "./IAVLegTrack.cfg"
      __default__.line_error_threshold = 0.02;
//#line 60 "./IAVLegTrack.cfg"
      __param_descriptions__.push_back(IAVLegTrackConfig::AbstractParamDescriptionConstPtr(new IAVLegTrackConfig::ParamDescription<double>("line_error_threshold", "double", 0, "Maximum allowed error during recursive line fitting.", "", &IAVLegTrackConfig::line_error_threshold)));
//#line 62 "./IAVLegTrack.cfg"
      __min__.max_leg_diameter = 0.0;
//#line 62 "./IAVLegTrack.cfg"
      __max__.max_leg_diameter = 10.0;
//#line 62 "./IAVLegTrack.cfg"
      __default__.max_leg_diameter = 0.02;
//#line 62 "./IAVLegTrack.cfg"
      __param_descriptions__.push_back(IAVLegTrackConfig::AbstractParamDescriptionConstPtr(new IAVLegTrackConfig::ParamDescription<double>("max_leg_diameter", "double", 0, "Maximum diameter of a leg", "", &IAVLegTrackConfig::max_leg_diameter)));
//#line 63 "./IAVLegTrack.cfg"
      __min__.min_leg_diameter = 0.0;
//#line 63 "./IAVLegTrack.cfg"
      __max__.min_leg_diameter = 10.0;
//#line 63 "./IAVLegTrack.cfg"
      __default__.min_leg_diameter = 0.04;
//#line 63 "./IAVLegTrack.cfg"
      __param_descriptions__.push_back(IAVLegTrackConfig::AbstractParamDescriptionConstPtr(new IAVLegTrackConfig::ParamDescription<double>("min_leg_diameter", "double", 0, "Minimum diameter of a leg", "", &IAVLegTrackConfig::min_leg_diameter)));
//#line 65 "./IAVLegTrack.cfg"
      __min__.do_circles = 0;
//#line 65 "./IAVLegTrack.cfg"
      __max__.do_circles = 1;
//#line 65 "./IAVLegTrack.cfg"
      __default__.do_circles = 1;
//#line 65 "./IAVLegTrack.cfg"
      __param_descriptions__.push_back(IAVLegTrackConfig::AbstractParamDescriptionConstPtr(new IAVLegTrackConfig::ParamDescription<bool>("do_circles", "bool", 0, "", "", &IAVLegTrackConfig::do_circles)));
//#line 66 "./IAVLegTrack.cfg"
      __min__.do_lines = 0;
//#line 66 "./IAVLegTrack.cfg"
      __max__.do_lines = 1;
//#line 66 "./IAVLegTrack.cfg"
      __default__.do_lines = 1;
//#line 66 "./IAVLegTrack.cfg"
      __param_descriptions__.push_back(IAVLegTrackConfig::AbstractParamDescriptionConstPtr(new IAVLegTrackConfig::ParamDescription<bool>("do_lines", "bool", 0, "", "", &IAVLegTrackConfig::do_lines)));
//#line 67 "./IAVLegTrack.cfg"
      __min__.do_legs = 0;
//#line 67 "./IAVLegTrack.cfg"
      __max__.do_legs = 1;
//#line 67 "./IAVLegTrack.cfg"
      __default__.do_legs = 1;
//#line 67 "./IAVLegTrack.cfg"
      __param_descriptions__.push_back(IAVLegTrackConfig::AbstractParamDescriptionConstPtr(new IAVLegTrackConfig::ParamDescription<bool>("do_legs", "bool", 0, "", "", &IAVLegTrackConfig::do_legs)));
//#line 68 "./IAVLegTrack.cfg"
      __min__.iav_do_lines = 0;
//#line 68 "./IAVLegTrack.cfg"
      __max__.iav_do_lines = 1;
//#line 68 "./IAVLegTrack.cfg"
      __default__.iav_do_lines = 1;
//#line 68 "./IAVLegTrack.cfg"
      __param_descriptions__.push_back(IAVLegTrackConfig::AbstractParamDescriptionConstPtr(new IAVLegTrackConfig::ParamDescription<bool>("iav_do_lines", "bool", 0, "", "", &IAVLegTrackConfig::iav_do_lines)));
//#line 69 "./IAVLegTrack.cfg"
      __min__.safe_circle_corners = 0;
//#line 69 "./IAVLegTrack.cfg"
      __max__.safe_circle_corners = 1;
//#line 69 "./IAVLegTrack.cfg"
      __default__.safe_circle_corners = 0;
//#line 69 "./IAVLegTrack.cfg"
      __param_descriptions__.push_back(IAVLegTrackConfig::AbstractParamDescriptionConstPtr(new IAVLegTrackConfig::ParamDescription<bool>("safe_circle_corners", "bool", 0, "", "", &IAVLegTrackConfig::safe_circle_corners)));
//#line 239 "/home/sblume/ros/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"
    
      for (std::vector<IAVLegTrackConfig::AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        __description_message__.parameters.push_back(**i);
      __max__.__toMessage__(__description_message__.max, __param_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__); 
    }
    std::vector<IAVLegTrackConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    IAVLegTrackConfig __max__;
    IAVLegTrackConfig __min__;
    IAVLegTrackConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;
    static const IAVLegTrackConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static IAVLegTrackConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &IAVLegTrackConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const IAVLegTrackConfig &IAVLegTrackConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const IAVLegTrackConfig &IAVLegTrackConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const IAVLegTrackConfig &IAVLegTrackConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<IAVLegTrackConfig::AbstractParamDescriptionConstPtr> &IAVLegTrackConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const IAVLegTrackConfigStatics *IAVLegTrackConfig::__get_statics__()
  {
    const static IAVLegTrackConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = IAVLegTrackConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __IAVLEGTRACKRECONFIGURATOR_H__
